import useRecipeStore from "@/store/useRecipeStore";
import useTagStore from "@/store/useTagStore";
import { RecipeForm } from "@/types/Recipe";
import { Tag } from "@/types/Tag";

const TAGS: Tag[] = [
  { id: 1, name: "Rapide" },
  { id: 2, name: "Healthy" },
  { id: 3, name: "Famille" },
  { id: 4, name: "Snack" },
  { id: 5, name: "Sucré" },
  { id: 6, name: "Four" },
  { id: 7, name: "Froid" },
];

const DATA: RecipeForm[] = [
  {
    photoUri: "https://picsum.photos/seed/spaghetti/400/300",
    name: "Spaghetti Bolognaise",
    category: "meat",
    grade: 4,
    tagIds: [1, 3],
    ingredients: [
      "spaghetti;1kg",
      "tomate;2",
      "viande hachée;500g",
      "oignon;1",
      "ail;1/2 gousse",
    ],
    servings: 4,
    cookingTime: 30,
    description: "Un classique italien savoureux et rapide à préparer.",
    link: "https://example.com/spaghetti-bolognaise",
  },
  {
    photoUri: "https://picsum.photos/seed/poulet/400/300",
    name: "Poulet rôti",
    category: "meat",
    grade: 5,
    tagIds: [3],
    ingredients: [
      "poulet entier;1",
      "huile d'olive;2c.s",
      "herbes de Provence",
      "sel",
      "poivre",
    ],
    servings: 4,
    cookingTime: 90,
    description: "Poulet rôti doré et juteux, parfait pour le dîner.",
    link: "https://example.com/poulet-roti",
  },
  {
    photoUri: "https://picsum.photos/seed/salade/400/300",
    name: "Salade César",
    category: "meat",
    grade: 5,
    tagIds: [2],
    ingredients: [
      "laitue",
      "poulet;400g",
      "parmesan",
      "croutons",
      "sauce César",
    ],
    servings: 2,
    cookingTime: 15,
    description: "Salade fraîche et croustillante avec une sauce savoureuse.",
    link: "https://example.com/salade-cesar",
  },
  {
    photoUri: "https://picsum.photos/seed/omelette/400/300",
    name: "Omelette aux fines herbes",
    category: "vegetarian",
    grade: 4,
    tagIds: [4],
    ingredients: ["œufs;4", "ciboulette", "persil", "sel", "poivre"],
    servings: 1,
    cookingTime: 10,
    description: "Rapide, simple et délicieux pour le petit-déjeuner.",
    link: "https://example.com/omelette-fines-herbes",
  },
  {
    photoUri: "https://picsum.photos/seed/tartelegumes/400/300",
    name: "Tarte aux légumes",
    category: "vegetarian",
    grade: 4,
    tagIds: [2, 4],
    ingredients: [
      "pâte brisée;1",
      "courgette;2",
      "poivron;1",
      "tomate;2",
      "fromage râpé;100g",
    ],
    servings: 4,
    cookingTime: 40,
    description: "Tarte légère et savoureuse pour un repas végétarien.",
    link: "https://example.com/tarte-legumes",
  },
  {
    photoUri: "https://picsum.photos/seed/saumon/400/300",
    name: "Filet de saumon au four",
    category: "fish",
    grade: 5,
    tagIds: [2, 3],
    ingredients: [
      "saumon;400g",
      "citron;1",
      "aneth",
      "huile d'olive;20cl",
      "sel",
    ],
    servings: 2,
    cookingTime: 25,
    description: "Saumon tendre et parfumé, cuit à la perfection.",
    link: "https://example.com/saumon-four",
  },
  {
    photoUri: "https://picsum.photos/seed/burger/400/300",
    name: "Burger végétarien",
    category: "vegetarian",
    grade: 4,
    tagIds: [1, 3],
    ingredients: [
      "pain à burger;4",
      "galette de légumes;4",
      "salade",
      "tomate;1",
      "fromage;400g",
    ],
    servings: 2,
    cookingTime: 20,
    description: "Burger savoureux et healthy pour tous.",
    link: "https://example.com/burger-vegetarien",
  },
  {
    photoUri: "https://picsum.photos/seed/tacos/400/300",
    name: "Tacos au poulet",
    category: "starter",
    grade: 5,
    tagIds: [1, 3],
    ingredients: [
      "tortillas;3",
      "poulet;400g",
      "salade;200g",
      "tomate;3",
      "sauce salsa;20cl",
    ],
    servings: 3,
    cookingTime: 20,
    description: "Tacos simples et délicieux pour un repas rapide.",
    link: "https://example.com/tacos-poulet",
  },
  {
    photoUri: "https://picsum.photos/seed/ratatouille/400/300",
    name: "Ratatouille",
    category: "dessert",
    grade: 5,
    tagIds: [2, 4],
    ingredients: [
      "aubergine;2",
      "courgette;3",
      "poivron;1",
      "tomate;4",
      "oignon;1",
    ],
    servings: 4,
    cookingTime: 50,
    description: "Plat provençal riche en légumes et en saveurs.",
    link: "https://example.com/ratatouille",
  },
  {
    photoUri: "https://picsum.photos/seed/steak/400/300",
    name: "Steak grillé",
    category: "meat",
    grade: 5,
    tagIds: [3],
    ingredients: [
      "steak;200g",
      "sel;1 pincée",
      "poivre;2 pincées",
      "huile d'olive;1 c.s",
    ],
    servings: 2,
    cookingTime: 15,
    description: "Steak tendre et juteux, parfait pour les amateurs de viande.",
    link: "https://example.com/steak-grille",
  },
];

export async function insertJdd() {
  const tagStore = useTagStore.getState();
  const recipeStore = useRecipeStore.getState();
  console.log("💾 Ajout du jeu de données");
  await Promise.all(TAGS.map((tag) => tagStore.addTag(tag.name)));
  await Promise.all(DATA.map((recipe) => recipeStore.addRecipe(recipe)));
}
